### ISSUE TITLE
일부 백엔드 통신에서 디스코드 유저의 서버 권한을 확인하는 중에 레이트리밋으로 인해 처리를 실패함 

### ISSUE THREAD

**Issue by ArpaAP** [InfiniteTeam/aztra-web#1]
### 1. 원인
대시보드 페이지가 프론트엔드에서 렌더링될 때 서버 이름과 아이콘을 표시하기 위해 디스코드 api에 서버 정보를 가져옵니다. 그와 동시에 환영 메시지 컴포넌트에서도 백엔드를 통해 간접적으로 디스코드 api에 같은 유저로 똑같이 서버 정보를 가져오므로, API 요청이 거의 동시에 일어나므로 레이트리밋이 발생해 백엔드 요청에 실패합니다.

### 2. 상세
백엔드: 백엔드에 프론트가 디스코드 Oauth2 토큰을 헤더에 담아 요청을 쏘면, 신원 확인 및 권한 확인을 위해 백엔드에서 헤더로 받은 토큰으로 디스코드 api에 서버 정보를 불러옴. (불러온 서버 정보에는 서버 아이디와 그 서버에서의 사용자 권한 정보가 담겨있으므로 요청하는 사람이 본인인지를 확인함.) 그 후 데이터베이스에서 환영 메시지 설정 데이터를 받아와 프론트에 전달.

### 3. 해결책
현재 프론트와 백엔드 두곳에서 동시에 디스코드 api 요청하는게 문제이므로 둘 중 하나만 남길 필요가 있음.

**Comment by gimon0330** [comment]
thinking

**Comment by ArpaAP** [comment]
## 현재 생각한 해결 방법

1. 백엔드 API에 프론트엔드 것도 한꺼번에 요청해서 프론트한테 보내서 실질적인 디코 요청은 1번으로 끝낸다
2. 백엔드는 디코 요청 없이 봇에서 웹서버를 구축해 가져온다 (단, 디코파이 객체를 다시 JSON으로 풀어서 보내야 하므로 생각못한 에러가 발생할 수 있음, 봇 성능 저하가 있을 수 있음(특히 디도스), 관리 복잡)
3. 백엔드에서 디코 api 에 요청 넣는 이유가 신원 확인과 권한 확인 위해서이므로 이를 자체 토큰 등의 인증으로 대체한다
4. 그냥 백엔드에서 요청 시도하고 리밋 걸렸다면 다시 시도함(느림)

**Comment by ArpaAP** [comment]
## 해결: 데이터 캐싱

우선 프론트엔드에서 요청하는 디스코드 API도 백엔드의 중계를 거치도록 바꾸었으며, 이로서 백엔드에서 모든 외부 요청을 처리하도록 했습니다. 그리고 백엔드에서는 디스코드 API 에서 성공적으로 응답을 받을 때 마다 내부 캐시에 이를 저장하도록 하고 레이트 리밋이 걸리는 경우만 캐시에 있는 기존 데이터로 대신 응답하는 방식으로 해결하였습니다.
